import type { PrinterProfile } from '../types/domain'

export const PRINTER_PROFILES: PrinterProfile[] = [
  {
    id: 'creality-ender-3-v3-plus',
    manufacturer: 'Creality',
    model: 'Ender-3 V3 Plus',
    displayName: 'Creality Ender-3 V3 Plus',
    bedSize: [300, 300, 330],
    nozzle: 0.4,
    filamentDiameter: 1.75,
    kinematics: 'coreXZ',
    gcodeDialect: 'klipper',
    maxVolumetricFlow: 12,
    maxFeedrate: 600,
    source: 'Creality Ender-3 V3 Plus official product and support specifications',
    sourceVersion: 'Accessed 2026-08-30',
    lastVerified: '2026-08-30 (machine envelope only)',
    requiresVerification: true,
    startGcode: [
      '; Conservative standard initialization - verify against installed Creality OS firmware',
      'G90 ; absolute XYZ',
      'M82 ; absolute extrusion',
      'G28 ; home all axes',
    ],
    endGcode: ['M104 S0', 'M140 S0', 'M107', 'G91', 'G1 Z10 F900', 'G90', 'M84'],
  },
  {
    id: 'generic-marlin-220',
    manufacturer: 'Generic',
    model: '3-Axis FDM 220',
    displayName: 'Generic Marlin · 220³',
    bedSize: [220, 220, 250],
    nozzle: 0.4,
    filamentDiameter: 1.75,
    kinematics: 'cartesian',
    gcodeDialect: 'marlin',
    maxVolumetricFlow: 10,
    maxFeedrate: 300,
    source: 'Built-in conservative research profile',
    sourceVersion: '0.1.0',
    lastVerified: '2026-08-30',
    requiresVerification: false,
    startGcode: ['G90 ; absolute XYZ', 'M82 ; absolute extrusion', 'G28 ; home all axes'],
    endGcode: ['M104 S0', 'M140 S0', 'M107', 'G91', 'G1 Z10 F900', 'G90', 'M84'],
  },
  {
    id: 'creality-k1-research',
    manufacturer: 'Creality',
    model: 'K1',
    displayName: 'Creality K1 · Research',
    bedSize: [220, 220, 250],
    nozzle: 0.4,
    filamentDiameter: 1.75,
    kinematics: 'coreXY',
    gcodeDialect: 'klipper',
    maxVolumetricFlow: 18,
    maxFeedrate: 600,
    source: 'Profile scaffold; verify against installed K1 firmware macros',
    sourceVersion: 'Unverified',
    lastVerified: 'Not verified',
    requiresVerification: true,
    startGcode: ['START_PRINT EXTRUDER_TEMP={NOZZLE_TEMP} BED_TEMP={BED_TEMP}'],
    endGcode: ['END_PRINT'],
  },
  {
    id: 'bambu-p1s-research',
    manufacturer: 'Bambu Lab',
    model: 'P1S',
    displayName: 'Bambu P1S · Research',
    bedSize: [256, 256, 256],
    nozzle: 0.4,
    filamentDiameter: 1.75,
    kinematics: 'coreXY',
    gcodeDialect: 'bambu',
    maxVolumetricFlow: 18,
    maxFeedrate: 500,
    source: 'Profile scaffold; official Bambu Studio startup sequence required',
    sourceVersion: 'Unverified',
    lastVerified: 'Not verified',
    requiresVerification: true,
    startGcode: ['; PROFILE REQUIRES VERIFICATION', 'G90', 'M82'],
    endGcode: ['; PROFILE REQUIRES VERIFICATION', 'M104 S0', 'M140 S0', 'M84'],
  },
]

export function getPrinterProfile(id: string): PrinterProfile {
  return PRINTER_PROFILES.find((profile) => profile.id === id) ?? PRINTER_PROFILES[0]
}
