import type { PrinterProfile, PrintSettings, Toolpath } from '../types/domain'

function substitute(line: string, settings: PrintSettings) {
  return line
    .replaceAll('{NOZZLE_TEMP}', String(settings.nozzleTemperature))
    .replaceAll('{BED_TEMP}', String(settings.bedTemperature))
}

const compact = (value: number, digits = 3) => Number(value.toFixed(digits))

export function generateGcode(
  toolpath: Toolpath,
  profile: PrinterProfile,
  settings: PrintSettings,
  projectName: string,
) {
  const [bedX, bedY] = profile.bedSize
  if (
    toolpath.orderedPoints.some((point) => point.segmentType === 'extrusion') &&
    settings.nozzleTemperature < profile.minExtrusionTemperature
  ) {
    throw new Error(
      `${profile.displayName} requires at least ${profile.minExtrusionTemperature} C before extrusion.`,
    )
  }

  const machinePoints = toolpath.orderedPoints.map((point) => ({
    x: point.x + bedX / 2,
    y: point.y + bedY / 2,
    z: point.z,
  }))
  const bounds = {
    minX: Math.min(...machinePoints.map((point) => point.x)),
    minY: Math.min(...machinePoints.map((point) => point.y)),
    minZ: Math.min(...machinePoints.map((point) => point.z)),
    maxX: Math.max(...machinePoints.map((point) => point.x)),
    maxY: Math.max(...machinePoints.map((point) => point.y)),
    maxZ: Math.max(...machinePoints.map((point) => point.z)),
  }
  const lines = [
    '; HEADER_BLOCK_START',
    '; generated by 260830_GcodeApp v0.3.0',
    `; total layer number: ${toolpath.constructionLayerCount + 1}`,
    `; filament_diameter: ${settings.filamentDiameter}`,
    `; max_z_height: ${bounds.maxZ.toFixed(2)}`,
    '; HEADER_BLOCK_END',
    '',
    `; MINX = ${bounds.minX.toFixed(2)}`,
    `; MINY = ${bounds.minY.toFixed(2)}`,
    `; MINZ = ${bounds.minZ.toFixed(2)}`,
    `; MAXX = ${bounds.maxX.toFixed(2)}`,
    `; MAXY = ${bounds.maxY.toFixed(2)}`,
    `; MAXZ = ${bounds.maxZ.toFixed(2)}`,
    '',
    '; EXECUTABLE_BLOCK_START',
    `; ${projectName}`,
    `; Printer: ${profile.displayName}`,
    '; Material: PLA',
    `; Toolpath: one continuous supported sinusoidal weave / ${toolpath.constructionLayerCount} helical turns`,
    `; Weave: ${toolpath.weaveAmplitude.toFixed(2)} mm amplitude / ${toolpath.weaveWavelength.toFixed(2)} mm wavelength / ${toolpath.jointCount} contact joints`,
    `; Calculated speed: ${toolpath.recommendedSpeed.toFixed(2)} mm/s / maximum vertical acceleration ${toolpath.maxVerticalAcceleration.toFixed(2)} mm/s2`,
    `; Profile source: ${profile.source}`,
  ]

  if (profile.requiresVerification) {
    lines.push('; WARNING: PROFILE REQUIRES VERIFICATION BEFORE MACHINE USE')
  }

  lines.push(...profile.startGcode.map((line) => substitute(line, settings)), 'G92 E0')

  let previousType: 'extrusion' | 'travel' | undefined
  let previousLayer = -1
  let previousCumulativeE = 0
  let currentFan = 0
  for (const point of toolpath.orderedPoints) {
    const x = compact(point.x + bedX / 2)
    const y = compact(point.y + bedY / 2)
    const z = compact(point.z)
    const f = Math.round(point.feedrate)
    if (point.segmentType === 'travel') {
      lines.push(`G0 X${x} Y${y} Z${z} F${f}`)
    } else {
      if (point.constructionLayer !== previousLayer) {
        lines.push(
          ';LAYER_CHANGE',
          `;Z:${z}`,
          `; construction layer ${point.constructionLayer} - ground-up continuous route`,
        )
        if (profile.extrusionMode === 'relative') lines.push('G92 E0')
        const desiredFan = point.constructionLayer === 0
          ? 0
          : Math.round((settings.fan / 100) * 255)
        if (desiredFan !== currentFan) {
          lines.push(`M106 S${desiredFan}`)
          currentFan = desiredFan
        }
        previousLayer = point.constructionLayer
      }
      if (previousType === 'travel') lines.push(`; begin path ${point.pathID}`)
      const extrusion = profile.extrusionMode === 'relative'
        ? Math.max(0, point.e - previousCumulativeE)
        : point.e
      lines.push(`G1 X${x} Y${y} Z${z} E${compact(extrusion, 5)} F${f}`)
      previousCumulativeE = point.e
    }
    previousType = point.segmentType
  }

  lines.push(
    ...profile.endGcode.map((line) => substitute(line, settings)),
    '; EXECUTABLE_BLOCK_END',
    '',
    `; filament used [mm] = ${toolpath.filamentLength.toFixed(2)}`,
    '; end of generated file',
  )
  return `${lines.join('\n')}\n`
}

export function generateToolpathCsv(toolpath: Toolpath) {
  const rows = ['index,x,y,z,e,speed,flow,type,support']
  toolpath.orderedPoints.forEach((point, index) => {
    rows.push([
      index,
      point.x.toFixed(4),
      point.y.toFixed(4),
      point.z.toFixed(4),
      point.e.toFixed(5),
      (point.feedrate / 60).toFixed(2),
      point.extrusionMultiplier.toFixed(3),
      point.segmentType,
      point.supportState,
    ].join(','))
  })
  return `${rows.join('\n')}\n`
}
