import type { PrinterProfile, PrintSettings, Toolpath } from '../types/domain'

function substitute(line: string, settings: PrintSettings) {
  return line
    .replaceAll('{NOZZLE_TEMP}', String(settings.nozzleTemperature))
    .replaceAll('{BED_TEMP}', String(settings.bedTemperature))
}

const compact = (value: number, digits = 3) => Number(value.toFixed(digits))

export function generateGcode(
  toolpath: Toolpath,
  profile: PrinterProfile,
  settings: PrintSettings,
  projectName: string,
) {
  const [bedX, bedY] = profile.bedSize
  const lines = [
    `; ${projectName}`,
    '; Generated by 260830_GcodeApp v0.1.0',
    `; Printer: ${profile.displayName}`,
    '; Material: PLA',
    `; Toolpath: one continuous extrusion route / ${toolpath.constructionLayerCount} ground-up layers at ${toolpath.constructionLift.toFixed(2)} mm maximum lift`,
    `; Skip joints: ${toolpath.skipJointCount} / maximum span ${toolpath.maxSkipSpan.toFixed(2)} mm`,
    `; Profile source: ${profile.source}`,
  ]

  if (profile.requiresVerification) {
    lines.push('; WARNING: PROFILE REQUIRES VERIFICATION BEFORE MACHINE USE')
  }

  lines.push(
    `M140 S${settings.bedTemperature}`,
    `M104 S${settings.nozzleTemperature}`,
    `M190 S${settings.bedTemperature}`,
    `M109 S${settings.nozzleTemperature}`,
    ...profile.startGcode.map((line) => substitute(line, settings)),
    'G92 E0',
    `M106 S${Math.round((settings.fan / 100) * 255)}`,
  )

  let previousType: 'extrusion' | 'travel' | undefined
  let previousLayer = -1
  for (const point of toolpath.orderedPoints) {
    const x = compact(point.x + bedX / 2)
    const y = compact(point.y + bedY / 2)
    const z = compact(point.z)
    const f = Math.round(point.feedrate)
    if (point.segmentType === 'travel') {
      lines.push(`G0 X${x} Y${y} Z${z} F${f}`)
    } else {
      if (point.constructionLayer !== previousLayer) {
        lines.push(`; construction layer ${point.constructionLayer} - ground-up continuous route`)
        previousLayer = point.constructionLayer
      }
      if (previousType === 'travel') lines.push(`; begin path ${point.pathID}`)
      lines.push(`G1 X${x} Y${y} Z${z} E${compact(point.e, 4)} F${f}`)
      if (point.jointType === 'skip-joint' && settings.jointDwellMs > 0) {
        lines.push(`G4 P${Math.round(settings.jointDwellMs)} ; PLA joint consolidation`)
      }
    }
    previousType = point.segmentType
  }

  lines.push(...profile.endGcode.map((line) => substitute(line, settings)), '; end of generated file')
  return `${lines.join('\n')}\n`
}

export function generateToolpathCsv(toolpath: Toolpath) {
  const rows = ['index,x,y,z,e,speed,flow,type,support']
  toolpath.orderedPoints.forEach((point, index) => {
    rows.push([
      index,
      point.x.toFixed(4),
      point.y.toFixed(4),
      point.z.toFixed(4),
      point.e.toFixed(5),
      (point.feedrate / 60).toFixed(2),
      point.extrusionMultiplier.toFixed(3),
      point.segmentType,
      point.supportState,
    ].join(','))
  })
  return `${rows.join('\n')}\n`
}
